[theme]
base = "light"
# Primary color for interactive elements
primaryColor = "#2E7D32"  

# Main background color
backgroundColor = "#FFFFF0"  

# Background color for sidebar and most widgets
secondaryBackgroundColor = "#F1F8E9"  # Light Mint - Secondary panels and cards

# Color of body text
textColor = "#263238"  # Dark Blue-Grey - Primary text

# Font family for all text
font = "sans serif"